common/types.go, consensus/clique/clique.go, consensus/consensus.go, consensus/datong/consensus.go, consensus/ethash/consensus.go, core/state/statedb.go, miner/worker.go
fix datong consensus for psn2
- fix bad block
- fix chain fork
- fix verifySeal
- fix header.diffculty
- fix statedb deepcopy
- fix tickets pool sort
=> fix datong consensus for psn2.0

consensus/datong/consensus.go
Update block time, adjust with two blocks time interval.
=>  Update block time, adjust with two blocks time interval

common/types.go, consensus/clique/clique.go, consensus/consensus.go, consensus/datong/consensus.go, consensus/ethash/consensus.go, core/state_transition.go, internal/ethapi/api_fsn.go, miner/worker.go
* update UpdateBlockBroadcast(args consistent with HaveBlockBroaded's) and calcDelayTime
* recalc selectedTime:remove repeat tickets with one miner
* update delaytime adjust factor
=> Uptate seal:delayTime and finalize:selectedTime

common/timelock.go, consensus/datong/consensus.go, core/state/state_object.go, core/state/statedb.go, miner/worker.go
- fixed eth.estimateGas() get gasLimit need block info when sync
- delete tickets before coinbase if selected miner did not Seal
- statedb.AllTickets() not return copyOfTickets()
- add deepCopy to BalancesHash/BalancesVal/TimeLockBalancesHash/TimeLockBalancesVal
- update ticketInfo and broad(func: updateSelectedTicketTime, haveSelectedTicketTime, UpdateBlockBroadcast, HaveBlockBroaded)
=> fix delayTime, consensus ticketSelected and add deepCopy.

cmd/efsn/main.go, cmd/efsn/usage.go, cmd/utils/flags.go, common/types.go, consensus/datong/consensus.go, core/blockchain.go, core/state/statedb.go, internal/ethapi/api_fsn.go, params/config.go
- fix engine: use datong, delete ethash
- fix no ticket to continue mining
- update block adjust time: maximum ±5s
- add AutoBuyTicket (bootargs: --autobt)
=> fix datong engine

consensus/datong/consensus.go, core/state_transition.go, core/tx_pool.go, internal/ethapi/api_fsn.go
- verify block time
- autoBuy ticket optimized
- update block time
- verify tickets: height, time and value
=> verify tickets and block time

core/state_transition.go, core/tx_pool.go
- validate buy ticket tx
- limit buy one ticket per block
=> validate buy ticket tx, limit buy one ticket per block

consensus/datong/consensus.go, core/block_validator.go, core/tx_pool.go, miner/worker.go
1. adjust diffculty calculation
2. enable PSN20 hardfork at height 90000
3. adjust delay time modifier and maximum number of deleted tickets
4. change the logic to return the time lock FSN to the ticket owner if his ticket is removed
=> PSN2.0 hardfork feature

QuickNodeSetup/fsnNode.sh
Removed duplicated code block which disables autobuy since the condition in the second block will never be true.
=> Duplicated code block disables autobuy function

consensus/datong/consensus.go
1. use header.Nonce to store ticket order
2. modify check block time logic, use header.Time instead of time.Now
3. adjust difficulty to keep different from each other
4. modify max block time to 10 min
=> Psn2.0 hardfork2 feature

common/types.go, consensus/datong/consensus.go, core/block_validator.go, core/blockchain.go, core/genesis.go, core/state/statedb.go, core/state_transition.go, core/vm/interface.go, internal/ethapi/api_fsn.go, miner/worker.go
1. use slice instead of map to store tickets in statedb
2. modify tickets encoding to bytes data content
3. update tickets encoding data once for each block
4. get rid of mining uncle related codes
=> Psn2.0 hardfork3 feature

common/timelock.go, common/types.go, consensus/datong/consensus.go, core/genesis.go, core/state_transition.go, internal/ethapi/api_fsn.go, internal/web3ext/web3ext.go
1. modify ticket price
2. check time lock must satisfy startTime <= endTime
=> Psn2.0 hardfork4 feature

common/big.go, common/size.go, common/timelock.go, common/types.go, common/utils.go, consensus/datong/consensus.go, core/block_validator.go, core/blockchain.go, core/evm.go, core/state/state_object.go, core/state/statedb.go, core/state_transition.go, core/tx_pool.go, core/vm/evm.go, core/vm/interface.go, internal/ethapi/api_fsn.go, miner/worker.go
1. redesign time lock items' storage
2. modify time lock start time to latest block time
3. clear expired time lock items when updating
4. check fsn call related params uniformly
5. clear expired swaps periodically
=> Psn2.0 hardfork5 feature

common/timelock.go
modify time lock display format as before, 
that is merge timestamp as long as possible, and then sort them by value decreasely.
```
eg: display [
{StartTime:101, EndTime:200,Value:30}
{StartTime:201, EndTime:300,Value:10}
{StartTime:301, EndTime:400,Value:50}]
as before in the following format: [
{StartTime:301, EndTime:400,Value:40}
{StartTime:101, EndTime:200,Value:20}
{StartTime:101, EndTime:400,Value:10}]
```
this modification does not change consensus, 
only change `GetTimeLockBalance` and `GetAllTimeLockBalances` APIs' outputs.
=> modify time lock display format as before

cmd/efsn/config.go, cmd/utils/flags.go, common/convert.go, common/timelock.go, common/types.go, common/utils.go, consensus/datong/consensus.go, core/blockchain.go, core/genesis.go, core/state/state_object.go, core/state/statedb.go, core/state_transition.go, core/tx_pool.go, core/types/block.go, core/vm/interface.go, eth/config.go, eth/downloader/downloader.go, eth/downloader/modes.go, eth/sync.go, internal/ethapi/api_fsn.go, miner/unconfirmed.go, miner/worker.go
1. store tickets in ticket-key-address account's storage
2. add TxPool::validateFsnCallTx to do more validation before adding to txpool
3. add fsn call fee for genasset/gennotation/timelockfunc/makeswap
=> improvements of tickets storage and code refactor

common/ticket.go, consensus/clique/clique.go, consensus/consensus.go, consensus/datong/consensus.go, consensus/datong/snapshot.go, consensus/ethash/consensus.go, core/blockchain.go, core/genesis.go, core/state/statedb.go, core/tx_pool.go, eth/downloader/modes.go, ethstats/ethstats.go, internal/ethapi/api_fsn.go, internal/web3ext/web3ext.go, miner/miner.go, miner/worker.go
1. add fsn.getSwap fsn.getMultiSwap api
2. modify fsn.getAsset, also accept tx hash as argument
3. disable archive gcmode as default
4. fix transfer notation
=> support non-archive gcmode

common/types.go, core/evm.go, core/state_transition.go, core/tx_pool.go, core/vm/evm.go, miner/worker.go
1. adjust fsn call fee
2. don't pick tx in mining if handleFsnCall meet error
=> adjust fsn call fee

cmd/efsn/accountcmd.go, common/types.go, core/state/state_object.go, core/state_transition.go, core/tx_list.go, core/tx_pool.go, internal/ethapi/api_fsn.go, internal/web3ext/web3ext.go, miner/worker.go
1. fix some api problem in testing
2. add new command 'account showkey' to show private key of a keystore file
=> fix some api problem in testing

cmd/efsn/chaincmd.go, cmd/efsn/consolecmd.go, cmd/efsn/main.go, cmd/efsn/usage.go, cmd/utils/flags.go, common/types.go, common/utils.go, consensus/datong/consensus.go, core/genesis.go, core/genesis_alloc.go, core/state/statedb.go, core/tx_pool.go, eth/api_backend.go, internal/ethapi/api_fsn.go, internal/ethapi/backend.go, internal/web3ext/web3ext.go, les/api_backend.go, miner/worker.go, params/bootnodes.go, params/config.go
1. add fsnbt api isAutoBuyTicket, startAutoBuyTicket and stopAutoBuyTicket
2. add develop network support, use --devnet to enable it
3. do not print error info if prepare header failed as having no ticket
4. don't stop docker container when use ctrl-c to exit viewNode
Note: this modification is compatible with v3.0.0, with no change to the consensus.
=> V3.0.0 fix - add fsnbt api isAutoBuyTicket, startAutoBuyTicket and stopAutoBuyTicket

QuickNodeSetup/fsnNode.sh
=> fsnNode.sh fixed

QuickNodeSetup/fsnNode.sh, cmd/efsn/main.go, cmd/efsn/usage.go, cmd/utils/flags.go, consensus/datong/checkpoints.go, consensus/datong/consensus.go, consensus/datong/report.go, core/block_validator.go, eth/api_backend.go, internal/ethapi/api_fsn.go, internal/web3ext/web3ext.go
1. add api fsn.getRetreatTickets
2. add api fsntx.buildSendTimeLockTx
3. add check points
4. update distro checks
5. don't return null pending block (fix eth_estimateGas)
=> add API and fix bug

QuickNodeSetup/fsnNode.sh
Enabled the mining configuration (enable/disable mining, to run a backup node for example) which was disabled because of a missing dependency which is now resolved.
=> fsnNode.sh: Enabled mining configuration
